using CronosReserva.Models;

namespace CronosReserva.Routes;

public static class ROTA_GET
{
    public static void MapGetRoutes(this WebApplication app)
    {
         var reservas = new List<Reserva>
         {
            new Reserva { Id = 1, Nome = "Ana Silva", Telefone = "(11) 91234-1001", DataInicio = new DateOnly(2025, 01, 10), DiasAlugados = 3, Tamanho = Tamanho.Medio, NomeLocal = "Salão Ouro Branco", ValorTotal = 3000, Descricao = "Salão amplo com capacidade para 200 pessoas e climatização completa" },
            new Reserva { Id = 2, Nome = "Bruno Almeida", Telefone = "(11) 91234-1002", DataInicio = new DateOnly(2025, 01, 15), DiasAlugados = 2, Tamanho = Tamanho.Pequeno, NomeLocal = "Espaço Bella Festa", ValorTotal = 1500, Descricao = "Ambiente moderno com iluminação de LED e pista de dança" },
            new Reserva { Id = 3, Nome = "Carla Ferreira", Telefone = "(11) 91234-1003", DataInicio = new DateOnly(2025, 02, 02), DiasAlugados = 4, Tamanho = Tamanho.Grande, NomeLocal = "Salão Imperial", ValorTotal = 5000, Descricao = "Espaço elegante com palco e cozinha industrial" },
            new Reserva { Id = 4, Nome = "Diego Souza", Telefone = "(11) 91234-1004", DataInicio = new DateOnly(2025, 02, 10), DiasAlugados = 1, Tamanho = Tamanho.Medio, NomeLocal = "Salão Jardim Encantado", ValorTotal = 3000, Descricao = "Área arborizada com jardim e pergolado para cerimônias" },
            new Reserva { Id = 5, Nome = "Eduarda Lima", Telefone = "(11) 91234-1005", DataInicio = new DateOnly(2025, 03, 05), DiasAlugados = 5, Tamanho = Tamanho.Medio, NomeLocal = "Espaço Premier", ValorTotal = 3000, Descricao = "Ambiente sofisticado com estrutura para eventos corporativos" },
            new Reserva { Id = 6, Nome = "Felipe Rocha", Telefone = "(11) 91234-1006", DataInicio = new DateOnly(2025, 03, 20), DiasAlugados = 2, Tamanho = Tamanho.Grande, NomeLocal = "Salão Diamante", ValorTotal = 5000, Descricao = "Salão com palco, camarim e iluminação profissional" },
            new Reserva { Id = 7, Nome = "Gabriela Torres", Telefone = "(11) 91234-1007", DataInicio = new DateOnly(2025, 04, 12), DiasAlugados = 3, Tamanho = Tamanho.Pequeno, NomeLocal = "Espaço Viva Eventos", ValorTotal = 1500, Descricao = "Salão versátil para festas de médio porte" },
            new Reserva { Id = 8, Nome = "Henrique Santos", Telefone = "(11) 91234-1008", DataInicio = new DateOnly(2025, 04, 25), DiasAlugados = 1, Tamanho = Tamanho.Grande, NomeLocal = "Salão Harmonia", ValorTotal = 5000, Descricao = "Espaço climatizado com estacionamento e área gourmet" },
            new Reserva { Id = 9, Nome = "Isabela Nunes", Telefone = "(11) 91234-1009", DataInicio = new DateOnly(2025, 05, 09), DiasAlugados = 4, Tamanho = Tamanho.Medio, NomeLocal = "Espaço Estilo & Festa", ValorTotal = 3000, Descricao = "Ambiente moderno e totalmente adaptável" },
            new Reserva { Id = 10, Nome = "João Carvalho", Telefone = "(11) 91234-1010", DataInicio = new DateOnly(2025, 05, 20), DiasAlugados = 2, Tamanho = Tamanho.Pequeno, NomeLocal = "Salão Crystal", ValorTotal = 1500, Descricao = "Salão com estrutura de som e iluminação integrada" },
            new Reserva { Id = 11, Nome = "Karina Mendes", Telefone = "(11) 91234-1011", DataInicio = new DateOnly(2025, 06, 02), DiasAlugados = 5, Tamanho = Tamanho.Grande, NomeLocal = "Espaço Real", ValorTotal = 5000, Descricao = "Ambiente climatizado com palco e cozinha equipada" },
            new Reserva { Id = 12, Nome = "Lucas Andrade", Telefone = "(11) 91234-1012", DataInicio = new DateOnly(2025, 06, 15), DiasAlugados = 1, Tamanho = Tamanho.Medio, NomeLocal = "Salão do Lago", ValorTotal = 3000, Descricao = "Vista para o lago e espaço externo para cerimônias" },
            new Reserva { Id = 13, Nome = "Mariana Costa", Telefone = "(11) 91234-1013", DataInicio = new DateOnly(2025, 07, 01), DiasAlugados = 3, Tamanho = Tamanho.Medio, NomeLocal = "Espaço Aurora", ValorTotal = 3000, Descricao = "Decoração moderna com painéis de LED" },
            new Reserva { Id = 14, Nome = "Nicolas Ribeiro", Telefone = "(11) 91234-1014", DataInicio = new DateOnly(2025, 07, 10), DiasAlugados = 2, Tamanho = Tamanho.Grande, NomeLocal = "Salão Elite", ValorTotal = 5000, Descricao = "Espaço premium com climatização e estrutura completa" },
            new Reserva { Id = 15, Nome = "Olívia Fernandes", Telefone = "(11) 91234-1015", DataInicio = new DateOnly(2025, 07, 22), DiasAlugados = 4, Tamanho = Tamanho.Medio, NomeLocal = "Espaço Bela Vista", ValorTotal = 3000, Descricao = "Vista panorâmica e área verde ao redor" },
            new Reserva { Id = 16, Nome = "Paulo Martins", Telefone = "(11) 91234-1016", DataInicio = new DateOnly(2025, 08, 03), DiasAlugados = 3, Tamanho = Tamanho.Grande, NomeLocal = "Salão Garden Hall", ValorTotal = 5000, Descricao = "Área para eventos ao ar livre com cobertura retrátil" },
            new Reserva { Id = 17, Nome = "Queila Barbosa", Telefone = "(11) 91234-1017", DataInicio = new DateOnly(2025, 08, 12), DiasAlugados = 5, Tamanho = Tamanho.Medio, NomeLocal = "Espaço Celebration", ValorTotal = 3000, Descricao = "Ambiente moderno e climatizado com decoração neutra" },
            new Reserva { Id = 18, Nome = "Rafael Castro", Telefone = "(11) 91234-1018", DataInicio = new DateOnly(2025, 08, 28), DiasAlugados = 1, Tamanho = Tamanho.Pequeno, NomeLocal = "Salão Villa Real", ValorTotal = 1500, Descricao = "Espaço rústico com acabamento em madeira" },
            new Reserva { Id = 19, Nome = "Sabrina Oliveira", Telefone = "(11) 91234-1019", DataInicio = new DateOnly(2025, 09, 07), DiasAlugados = 4, Tamanho = Tamanho.Grande, NomeLocal = "Espaço Golden", ValorTotal = 5000, Descricao = "Salão luxuoso com palco, pista e iluminação cenográfica" },
            new Reserva { Id = 20, Nome = "Thiago Lopes", Telefone = "(11) 91234-1020", DataInicio = new DateOnly(2025, 09, 15), DiasAlugados = 2, Tamanho = Tamanho.Medio, NomeLocal = "Salão Riviera", ValorTotal = 3000, Descricao = "Ambiente clean e climatizado com estrutura moderna" },
            new Reserva { Id = 20, Nome = "Thiago Lopes", Telefone = "(11) 91234-1020", DataInicio = new DateOnly(2025, 09, 15), DiasAlugados = 1, Tamanho = Tamanho.Medio, NomeLocal = "Salão Riviera", ValorTotal = 3000, Descricao = "Ambiente clean e climatizado com estrutura moderna" },
            new Reserva { Id = 21, Nome = "Úrsula Matos", Telefone = "(11) 91234-1021", DataInicio = new DateOnly(2025, 09, 25), DiasAlugados = 2, Tamanho = Tamanho.Medio, NomeLocal = "Espaço Diamantina", ValorTotal = 6000, Descricao = "Espaço aconchegante ideal para eventos familiares" },
            new Reserva { Id = 22, Nome = "Victor Gomes", Telefone = "(11) 91234-1022", DataInicio = new DateOnly(2025, 10, 01), DiasAlugados = 3, Tamanho = Tamanho.Grande, NomeLocal = "Salão Mirante", ValorTotal = 15000, Descricao = "Vista panorâmica da cidade e estacionamento privativo" },
            new Reserva { Id = 23, Nome = "Wellington Azevedo", Telefone = "(11) 91234-1023", DataInicio = new DateOnly(2025, 10, 08), DiasAlugados = 1, Tamanho = Tamanho.Pequeno, NomeLocal = "Espaço Platinum", ValorTotal = 1500, Descricao = "Ambiente moderno com estrutura para casamentos" },
            new Reserva { Id = 24, Nome = "Xênia Duarte", Telefone = "(11) 91234-1024", DataInicio = new DateOnly(2025, 10, 15), DiasAlugados = 2, Tamanho = Tamanho.Medio, NomeLocal = "Salão Roma", ValorTotal = 6000, Descricao = "Decoração clássica e iluminação quente" },
            new Reserva { Id = 25, Nome = "Yasmin Barros", Telefone = "(11) 91234-1025", DataInicio = new DateOnly(2025, 10, 22), DiasAlugados = 3, Tamanho = Tamanho.Medio, NomeLocal = "Espaço Magnólia", ValorTotal = 9000, Descricao = "Salão com área verde e estacionamento amplo" },
            new Reserva { Id = 26, Nome = "Zeca Moraes", Telefone = "(11) 91234-1026", DataInicio = new DateOnly(2025, 10, 29), DiasAlugados = 1, Tamanho = Tamanho.Medio, NomeLocal = "Salão Harmonia II", ValorTotal = 3000, Descricao = "Ambiente climatizado com isolamento acústico" },
            new Reserva { Id = 27, Nome = "Alice Moreira", Telefone = "(11) 91234-1027", DataInicio = new DateOnly(2025, 11, 05), DiasAlugados = 2, Tamanho = Tamanho.Grande, NomeLocal = "Espaço Grand Palace", ValorTotal = 10000, Descricao = "Salão luxuoso com palco e área VIP" },
            new Reserva { Id = 28, Nome = "Brenda Tavares", Telefone = "(11) 91234-1028", DataInicio = new DateOnly(2025, 11, 15), DiasAlugados = 3, Tamanho = Tamanho.Medio, NomeLocal = "Salão Versatille", ValorTotal = 9000, Descricao = "Espaço modular adaptável para qualquer tipo de evento" },
            new Reserva { Id = 29, Nome = "Caio Nogueira", Telefone = "(11) 91234-1029", DataInicio = new DateOnly(2025, 11, 25), DiasAlugados = 1, Tamanho = Tamanho.Medio, NomeLocal = "Espaço Allegro", ValorTotal = 3000, Descricao = "Ambiente acolhedor e moderno com som ambiente" },
            new Reserva { Id = 30, Nome = "Daniela Prado", Telefone = "(11) 91234-1030", DataInicio = new DateOnly(2025, 12, 05), DiasAlugados = 2, Tamanho = Tamanho.Grande, NomeLocal = "Salão Imperial II", ValorTotal = 10000, Descricao = "Espaço nobre com palco, jardim e estrutura completa" },
            new Reserva { Id = 31, Nome = "Eduardo Silva", Telefone = "(11) 91234-1031", DataInicio = new DateOnly(2026, 01, 10), DiasAlugados = 3, Tamanho = Tamanho.Medio, NomeLocal = "Espaço Aurora II", ValorTotal = 9000, Descricao = "Ambiente moderno com decoração elegante e iluminação personalizada" },
            new Reserva { Id = 32, Nome = "Fernanda Reis", Telefone = "(11) 91234-1032", DataInicio = new DateOnly(2026, 01, 18), DiasAlugados = 1, Tamanho = Tamanho.Pequeno, NomeLocal = "Salão Bela Arte", ValorTotal = 1500, Descricao = "Espaço climatizado ideal para pequenas recepções" },
            new Reserva { Id = 33, Nome = "Gustavo Ramos", Telefone = "(11) 91234-1033", DataInicio = new DateOnly(2026, 01, 28), DiasAlugados = 2, Tamanho = Tamanho.Grande, NomeLocal = "Espaço Monte Carlo", ValorTotal = 10000, Descricao = "Ambiente sofisticado com estrutura de som e iluminação" },
            new Reserva { Id = 34, Nome = "Helena Cardoso", Telefone = "(11) 91234-1034", DataInicio = new DateOnly(2026, 02, 05), DiasAlugados = 3, Tamanho = Tamanho.Grande, NomeLocal = "Salão Royal Garden", ValorTotal = 15000, Descricao = "Área ajardinada com gazebo e fonte decorativa" },
            new Reserva { Id = 35, Nome = "Igor Santos", Telefone = "(11) 91234-1035", DataInicio = new DateOnly(2026, 02, 12), DiasAlugados = 1, Tamanho = Tamanho.Medio, NomeLocal = "Espaço Village", ValorTotal = 3000, Descricao = "Espaço moderno com estacionamento amplo" },
            new Reserva { Id = 36, Nome = "Júlia Freitas", Telefone = "(11) 91234-1036", DataInicio = new DateOnly(2026, 02, 25), DiasAlugados = 2, Tamanho = Tamanho.Grande, NomeLocal = "Salão Premier II", ValorTotal = 10000, Descricao = "Salão climatizado com estrutura completa para eventos" },
            new Reserva { Id = 37, Nome = "Kleber Batista", Telefone = "(11) 91234-1037", DataInicio = new DateOnly(2026, 03, 05), DiasAlugados = 3, Tamanho = Tamanho.Medio, NomeLocal = "Espaço Vivace", ValorTotal = 9000, Descricao = "Ambiente moderno com área externa para coquetéis" },
            new Reserva { Id = 38, Nome = "Larissa Cunha", Telefone = "(11) 91234-1038", DataInicio = new DateOnly(2026, 03, 12), DiasAlugados = 1, Tamanho = Tamanho.Grande, NomeLocal = "Salão Riviera II", ValorTotal = 5000, Descricao = "Espaço elegante com palco e iluminação de destaque" },
            new Reserva { Id = 39, Nome = "Marcelo Peixoto", Telefone = "(11) 91234-1039", DataInicio = new DateOnly(2026, 03, 22), DiasAlugados = 2, Tamanho = Tamanho.Medio, NomeLocal = "Espaço Allegra", ValorTotal = 6000, Descricao = "Ambiente acolhedor ideal para aniversários e formaturas" },
            new Reserva { Id = 40, Nome = "Natália Ribeiro", Telefone = "(11) 91234-1040", DataInicio = new DateOnly(2026, 04, 02), DiasAlugados = 3, Tamanho = Tamanho.Grande, NomeLocal = "Salão Ouro Branco II", ValorTotal = 15000, Descricao = "Salão nobre com vista panorâmica e climatização total" },
            new Reserva { Id = 41, Nome = "Otávio Martins", Telefone = "(11) 91234-1041", DataInicio = new DateOnly(2026, 04, 10), DiasAlugados = 4, Tamanho = Tamanho.Medio, NomeLocal = "Espaço Horizonte", ValorTotal = 12000, Descricao = "Ambiente moderno com área externa integrada" },
            new Reserva { Id = 42, Nome = "Paula Andrade", Telefone = "(11) 91234-1042", DataInicio = new DateOnly(2026, 04, 18), DiasAlugados = 2, Tamanho = Tamanho.Pequeno, NomeLocal = "Salão Vila Bella", ValorTotal = 3000, Descricao = "Espaço acolhedor ideal para pequenas cerimônias" },
            new Reserva { Id = 43, Nome = "Queila Moura", Telefone = "(11) 91234-1043", DataInicio = new DateOnly(2026, 04, 27), DiasAlugados = 5, Tamanho = Tamanho.Grande, NomeLocal = "Espaço Real Prime", ValorTotal = 25000, Descricao = "Estrutura completa para grandes eventos corporativos" },
            new Reserva { Id = 44, Nome = "Rogério Castro", Telefone = "(11) 91234-1044", DataInicio = new DateOnly(2026, 05, 06), DiasAlugados = 1, Tamanho = Tamanho.Medio, NomeLocal = "Salão Céu Azul", ValorTotal = 3000, Descricao = "Decoração clean e climatização total" },
            new Reserva { Id = 45, Nome = "Sabrina Torres", Telefone = "(11) 91234-1045", DataInicio = new DateOnly(2026, 05, 14), DiasAlugados = 3, Tamanho = Tamanho.Grande, NomeLocal = "Espaço Lux Garden", ValorTotal = 15000, Descricao = "Área externa ajardinada ideal para casamentos" },
            new Reserva { Id = 46, Nome = "Tales Mourão", Telefone = "(11) 91234-1046", DataInicio = new DateOnly(2026, 05, 22), DiasAlugados = 2, Tamanho = Tamanho.Medio, NomeLocal = "Salão Vivaz", ValorTotal = 6000, Descricao = "Ambiente flexível com infraestrutura de som" },
            new Reserva { Id = 47, Nome = "Uélida Paes", Telefone = "(11) 91234-1047", DataInicio = new DateOnly(2026, 05, 30), DiasAlugados = 4, Tamanho = Tamanho.Pequeno, NomeLocal = "Espaço Harmonia", ValorTotal = 6000, Descricao = "Ambiente intimista ideal para aniversários" },
            new Reserva { Id = 48, Nome = "Vagner Costa", Telefone = "(11) 91234-1048", DataInicio = new DateOnly(2026, 06, 08), DiasAlugados = 1, Tamanho = Tamanho.Grande, NomeLocal = "Salão Magnific", ValorTotal = 5000, Descricao = "Salão amplo com palco e iluminação profissional" },
            new Reserva { Id = 49, Nome = "Wesley Pires", Telefone = "(11) 91234-1049", DataInicio = new DateOnly(2026, 06, 17), DiasAlugados = 5, Tamanho = Tamanho.Medio, NomeLocal = "Espaço Cristal", ValorTotal = 15000, Descricao = "Design elegante com espaço para buffet" },
            new Reserva { Id = 50, Nome = "Xavier Freire", Telefone = "(11) 91234-1050)", DataInicio = new DateOnly(2026, 06, 26), DiasAlugados = 3, Tamanho = Tamanho.Medio, NomeLocal = "Salão Milano", ValorTotal = 9000, Descricao = "Ambiente moderno e climatizado" },
            new Reserva { Id = 51, Nome = "Yago Barreto", Telefone = "(11) 91234-1051", DataInicio = new DateOnly(2026, 07, 05), DiasAlugados = 2, Tamanho = Tamanho.Grande, NomeLocal = "Espaço Royal Prime", ValorTotal = 10000, Descricao = "Estrutura completa com área VIP" },
            new Reserva { Id = 52, Nome = "Zilda Monteiro", Telefone = "(11) 91234-1052", DataInicio = new DateOnly(2026, 07, 12), DiasAlugados = 5, Tamanho = Tamanho.Pequeno, NomeLocal = "Salão Floratta", ValorTotal = 7500, Descricao = "Espaço aconchegante com decoração rústica" },
            new Reserva { Id = 53, Nome = "Adriano Porto", Telefone = "(11) 91234-1053", DataInicio = new DateOnly(2026, 07, 22), DiasAlugados = 1, Tamanho = Tamanho.Medio, NomeLocal = "Espaço Safira", ValorTotal = 3000, Descricao = "Ambiente luxuoso com iluminação decorativa" },
            new Reserva { Id = 54, Nome = "Bianca Guedes", Telefone = "(11) 91234-1054", DataInicio = new DateOnly(2026, 08, 01), DiasAlugados = 4, Tamanho = Tamanho.Grande, NomeLocal = "Salão Grand Elite", ValorTotal = 20000, Descricao = "Salão imponente com entrada triunfal" },
            new Reserva { Id = 55, Nome = "Cael Santos", Telefone = "(11) 91234-1055", DataInicio = new DateOnly(2026, 08, 10), DiasAlugados = 1, Tamanho = Tamanho.Pequeno, NomeLocal = "Espaço Verona", ValorTotal = 1500, Descricao = "Ambiente simples e elegante" },
            new Reserva { Id = 56, Nome = "Dara Moura", Telefone = "(11) 91234-1056", DataInicio = new DateOnly(2026, 08, 19), DiasAlugados = 3, Tamanho = Tamanho.Medio, NomeLocal = "Salão Cristal Azul", ValorTotal = 9000, Descricao = "Decoração delicada com iluminação suave" },
            new Reserva { Id = 57, Nome = "Elen Carvalho", Telefone = "(11) 91234-1057", DataInicio = new DateOnly(2026, 08, 27), DiasAlugados = 2, Tamanho = Tamanho.Grande, NomeLocal = "Espaço Supreme", ValorTotal = 10000, Descricao = "Sala ampla com acústica profissional" },
            new Reserva { Id = 58, Nome = "Fabiano Lopes", Telefone = "(11) 91234-1058", DataInicio = new DateOnly(2026, 09, 05), DiasAlugados = 5, Tamanho = Tamanho.Medio, NomeLocal = "Salão Diamante", ValorTotal = 15000, Descricao = "Ambiente sofisticado com bar integrado" },
            new Reserva { Id = 59, Nome = "Giovanna Torres", Telefone = "(11) 91234-1059", DataInicio = new DateOnly(2026, 09, 14), DiasAlugados = 4, Tamanho = Tamanho.Pequeno, NomeLocal = "Espaço Harmonia II", ValorTotal = 6000, Descricao = "Local acolhedor para festas infantis" },
            new Reserva { Id = 60, Nome = "Henrique Paz", Telefone = "(11) 91234-1060", DataInicio = new DateOnly(2026, 09, 24), DiasAlugados = 3, Tamanho = Tamanho.Grande, NomeLocal = "Salão Platinum II", ValorTotal = 15000, Descricao = "Salão completo com palco e iluminação premium" },
            new Reserva { Id = 61, Nome = "Isabel Fonseca", Telefone = "(11) 91234-1061", DataInicio = new DateOnly(2026, 10, 03), DiasAlugados = 1, Tamanho = Tamanho.Medio, NomeLocal = "Espaço Angelus", ValorTotal = 3000, Descricao = "Ambiente clean com lounge externo" },
            new Reserva { Id = 62, Nome = "Jonas Ribeiro", Telefone = "(11) 91234-1062", DataInicio = new DateOnly(2026, 10, 12), DiasAlugados = 4, Tamanho = Tamanho.Grande, NomeLocal = "Salão Luz Dourada", ValorTotal = 20000, Descricao = "Ambiente luxuoso com vista panorâmica" },
            new Reserva { Id = 63, Nome = "Karen Duarte", Telefone = "(11) 91234-1063", DataInicio = new DateOnly(2026, 10, 21), DiasAlugados = 2, Tamanho = Tamanho.Pequeno, NomeLocal = "Espaço Primavera", ValorTotal = 3000, Descricao = "Decoração floral e ambiente acolhedor" },
            new Reserva { Id = 64, Nome = "Leandro Nunes", Telefone = "(11) 91234-1064", DataInicio = new DateOnly(2026, 10, 29), DiasAlugados = 5, Tamanho = Tamanho.Medio, NomeLocal = "Salão Rubi", ValorTotal = 15000, Descricao = "Espaço para eventos corporativos" },
            new Reserva { Id = 65, Nome = "Mélani Cabral", Telefone = "(11) 91234-1065", DataInicio = new DateOnly(2026, 11, 08), DiasAlugados = 3, Tamanho = Tamanho.Pequeno, NomeLocal = "Espaço Luna", ValorTotal = 4500, Descricao = "Ambiente charmoso para mini weddings" },
            new Reserva { Id = 66, Nome = "Nicolas Prado", Telefone = "(11) 91234-1066", DataInicio = new DateOnly(2026, 11, 18), DiasAlugados = 4, Tamanho = Tamanho.Grande, NomeLocal = "Salão Imperial III", ValorTotal = 20000, Descricao = "Salão elegante com jardim iluminado" },
            new Reserva { Id = 67, Nome = "Olívia Castro", Telefone = "(11) 91234-1067", DataInicio = new DateOnly(2026, 11, 26), DiasAlugados = 2, Tamanho = Tamanho.Medio, NomeLocal = "Espaço Vila Nova", ValorTotal = 6000, Descricao = "Ambiente espaçoso com área externa" },
            new Reserva { Id = 68, Nome = "Pietro Lima", Telefone = "(11) 91234-1068", DataInicio = new DateOnly(2026, 12, 06), DiasAlugados = 1, Tamanho = Tamanho.Grande, NomeLocal = "Salão Opus", ValorTotal = 5000, Descricao = "Infraestrutura completa com acústica profissional" },
            new Reserva { Id = 69, Nome = "Quitéria Gomes", Telefone = "(11) 91234-1069", DataInicio = new DateOnly(2026, 12, 15), DiasAlugados = 5, Tamanho = Tamanho.Pequeno, NomeLocal = "Espaço Toscana", ValorTotal = 7500, Descricao = "Local encantador com estilo europeu" },
            new Reserva { Id = 70, Nome = "Rafael Bolzan", Telefone = "(11) 91234-1070", DataInicio = new DateOnly(2026, 12, 23), DiasAlugados = 4, Tamanho = Tamanho.Medio, NomeLocal = "Salão Safira II", ValorTotal = 12000, Descricao = "Espaço amplo com decoração moderna" },
            new Reserva { Id = 71, Nome = "Sara Lemos", Telefone = "(11) 91234-1071", DataInicio = new DateOnly(2027, 01, 03), DiasAlugados = 3, Tamanho = Tamanho.Grande, NomeLocal = "Espaço Eleganz", ValorTotal = 15000, Descricao = "Ambiente sofisticado e climatizado" },
            new Reserva { Id = 72, Nome = "Tiago Almeida", Telefone = "(11) 91234-1072", DataInicio = new DateOnly(2027, 01, 12), DiasAlugados = 2, Tamanho = Tamanho.Medio, NomeLocal = "Salão Urbano", ValorTotal = 6000, Descricao = "Estilo industrial elegante" },
            new Reserva { Id = 73, Nome = "Ursula Klein", Telefone = "(11) 91234-1073", DataInicio = new DateOnly(2027, 01, 20), DiasAlugados = 1, Tamanho = Tamanho.Pequeno, NomeLocal = "Espaço Inspire", ValorTotal = 1500, Descricao = "Ambiente tranquilo para eventos íntimos" },
            new Reserva { Id = 74, Nome = "Vitor Hugo", Telefone = "(11) 91234-1074", DataInicio = new DateOnly(2027, 01, 29), DiasAlugados = 5, Tamanho = Tamanho.Grande, NomeLocal = "Salão Infinity", ValorTotal = 25000, Descricao = "Espaço grandioso para mega eventos" },
            new Reserva { Id = 75, Nome = "Willian Queiroz", Telefone = "(11) 91234-1075", DataInicio = new DateOnly(2027, 02, 07), DiasAlugados = 3, Tamanho = Tamanho.Medio, NomeLocal = "Espaço Prisma", ValorTotal = 9000, Descricao = "Local versátil para festas e reuniões" },
            new Reserva { Id = 76, Nome = "Ximena Lopes", Telefone = "(11) 91234-1076", DataInicio = new DateOnly(2027, 02, 15), DiasAlugados = 4, Tamanho = Tamanho.Pequeno, NomeLocal = "Salão Aurora", ValorTotal = 6000, Descricao = "Espaço iluminado com decoração delicada" },
            new Reserva { Id = 77, Nome = "Yuri Fernandes", Telefone = "(11) 91234-1077", DataInicio = new DateOnly(2027, 02, 25), DiasAlugados = 2, Tamanho = Tamanho.Grande, NomeLocal = "Espaço Golden Hall", ValorTotal = 10000, Descricao = "Salão luxuoso com acessos exclusivos" },
            new Reserva { Id = 78, Nome = "Zoraide Borges", Telefone = "(11) 91234-1078", DataInicio = new DateOnly(2027, 03, 06), DiasAlugados = 1, Tamanho = Tamanho.Medio, NomeLocal = "Salão Riviera III", ValorTotal = 3000, Descricao = "Ambiente moderno e climatizado" },
            new Reserva { Id = 79, Nome = "Alan Ferreira", Telefone = "(11) 91234-1079", DataInicio = new DateOnly(2027, 03, 15), DiasAlugados = 5, Tamanho = Tamanho.Grande, NomeLocal = "Espaço Premier III", ValorTotal = 25000, Descricao = "Infraestrutura completa para grandes eventos" },
            new Reserva { Id = 80, Nome = "Beatriz Campos", Telefone = "(11) 91234-1080", DataInicio = new DateOnly(2027, 03, 25), DiasAlugados = 3, Tamanho = Tamanho.Medio, NomeLocal = "Salão Garden Palace", ValorTotal = 9000, Descricao = "Ambiente elegante com jardim integrado" },

         };
               app.MapGet("/", () => "CRONOS(API) de Reservas em funcionamento!");

        app.MapGet("/reserva", () => reservas);

        app.MapGet("/reserva/{id}", (int id) =>
        {
            var reserva = reservas.FirstOrDefault(r => r.Id == id);
            return reserva != null ? Results.Ok(reserva) : Results.NotFound("Reserva não encontrada.");
        });
    }
}